# Generated by Django 4.1.6 on 2024-12-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('Fashion', 'Fashion'), ('Toys', 'Toys'), ('Electronics', 'Electronics'), ('Home', 'Home'), ('Sports', 'Sports'), ('Beauty', 'Beauty'), ('Health', 'Health')], max_length=11),
        ),
    ]
