# Generated by Django 4.1.6 on 2024-12-08 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_listing_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='won',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='won', to='auctions.listing'),
        ),
    ]
