# Generated by Django 4.1.6 on 2024-12-08 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_user_won'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='won',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won', to='auctions.listing'),
        ),
    ]
