# Generated by Django 4.1.6 on 2024-12-08 20:46

from django.db import migrations

def set_null_for_won(apps, schema_editor):
    User = apps.get_model('auctions', 'User')
    for user in User.objects.all():
        user.won = None
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_user_won'),
    ]

    operations = [
        migrations.RunPython(set_null_for_won),
    ]
