# Generated by Django 4.1.6 on 2024-12-08 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20241208_2246'),
    ]

    operations = [
    ]
